services:
  backend:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    volumes:
      - .:/workspace:cached
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=true # Required for hot reload in containers
    networks:
      - dev-network

  frontend:
    image: node:20-bookworm
    command: tail -f /dev/null
    volumes:
      - ./frontend:/workspace/frontend:cached
      # Isolate node_modules to avoid host OS conflicts
      - /workspace/frontend/node_modules
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge